language: ruby

rvm:
- 2.3.0

install: gem install ruby_dep:1.3.1 jekyll jekyll-feed jekyll-paginate jekyll-sitemap jekyll-seo-tag jemoji html-proofer minitest
script: jekyll serve --baseurl "" --detach && htmlproofer ./_site --disable-external --empty-alt-ignore

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true JEKYLL_ENV=production
